/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:a5c3fcc4-55b1-49b8-81e7-887c83fc4c01",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_VNxNdmgV6",
    "aws_user_pools_web_client_id": "6f9lajgoqb2jihfnh6dearvres",
    "oauth": {}
};


export default awsmobile;
